[package]
name = "phrase-guesser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
winresource = "0.1.17"
static_vcruntime = "2.0"
